### ISSUE TITLE
GHA workflows for Packer builds for AWS AMI

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/infra#797]
```[tasklist]
### Tasks
- [ ] Create GHA workflows for building the AMIs for AWS
- [ ] Ensure AMIs in 3 regions
- [ ] Create terraform resources using [channel](https://registry.terraform.io/providers/hashicorp/hcp/latest/docs/resources/packer_channel) and [channel assignment](https://registry.terraform.io/providers/hashicorp/hcp/latest/docs/resources/packer_channel_assignment) and automate updating via GHA
- [ ] Explore HCP Packer run task to potentially automate instance refresh on AWS ASG?
```
